name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2

      - name: Install Dependencies
        run: yarn install

      - name: Next.js Build
        run: yarn build
